import os
import io
import pathlib
import zipfile
import pandas as pd
import datetime as dt
import streamlit as st
import carbonatix as cx

st.markdown('# Carbonatix')

st.markdown('### Input Data')
uploaded_file = st.file_uploader(
	label = 'rawdata',
)

_anchors_df = pd.DataFrame(
	[
		dict(Sample = 'IAEA603', d13C_VPDB = '2.0', d18O_VPDB = '-2.0'),
		dict(Sample = 'NBS18', d13C_VPDB = '-5.0', d18O_VPDB = '-23.0'),
		dict(Sample = 'NBS 18', d13C_VPDB = '-5.0', d18O_VPDB = '-23.0'),
		dict(Sample = 'NBS 19', d13C_VPDB = '2.0', d18O_VPDB = '-2.0'),
		dict(Sample = '603-1', d13C_VPDB = '2.0', d18O_VPDB = '-2.0'),
	],
)

st.markdown('### Anchors')
anchors_df = st.data_editor(
	_anchors_df,
	hide_index = True,
	num_rows = 'dynamic',
	column_config = {
		'd13C_VPDB': st.column_config.NumberColumn('δ13C_VPDB', format = '%+.3f'),
		'd18O_VPDB': st.column_config.NumberColumn('δ18O_VPDB', format = '%+.3f'),
	}
)

if uploaded_file:

	here = pathlib.Path(os.path.abspath(os.path.dirname(__file__)))
	
	cx.process(
		rawdata = uploaded_file,
		anchors_df = anchors_df,
	)

	buf = io.BytesIO()

	readme = f"""
This zipfile was generated by carbonatix on {dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.

To reprocess the data, run the following command from the root of this directory:

uv run carbonatix -i 'input/{uploaded_file.name}' -a 'input/anchors.csv'
"""

	with zipfile.ZipFile(buf, 'x') as dl_zip:
		dl_zip.writestr('readme.txt', readme[1:])
		with open(here / 'assets/pyproject.toml') as fid:
			dl_zip.writestr('pyproject.toml', fid.read())
		with open(here / 'assets/uv.lock') as fid:
			dl_zip.writestr('uv.lock', fid.read())
		uploaded_file.seek(0)
		dl_zip.writestr(f'input/{uploaded_file.name}', uploaded_file.read())
		with io.BytesIO() as fid:
			anchors_df.to_csv(fid, index = False)
			fid.seek(0)
			dl_zip.writestr(f'input/anchors.csv', fid.read())

	st.download_button(
		label = 'Download zip',
		data = buf.getvalue(),
		file_name = 'carbonatix-results.zip',
		mime = 'application/zip',
		)
